/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AuthCookieSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IntervalServer": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "IntervalVpc": {
      "type": "sst.aws.Vpc"
    }
    "SecretValue": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WssApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
